# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='subject',
        ),
    ]
