# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0002_remove_response_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_text', models.CharField(max_length=200)),
                ('control_condition', models.CharField(max_length=200)),
                ('probe_number', models.IntegerField(verbose_name='Порядковый номер предложения')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
