# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0005_auto_20170919_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='probe_control_conditions',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='code_name',
            field=models.CharField(max_length=15),
        ),
    ]
