# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0007_auto_20170920_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='languages',
            field=models.CharField(default='нет', max_length=30),
        ),
    ]
