# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0008_subject_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='block_count',
            field=models.IntegerField(default=1, verbose_name='Количество блоков в условии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probe',
            name='block_number',
            field=models.IntegerField(default=1, verbose_name='Номер блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probe',
            name='probes_in_block',
            field=models.IntegerField(default=5, verbose_name='Количество проб в блоке'),
            preserve_default=False,
        ),
    ]
