# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0010_auto_20171008_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probe',
            name='block_count',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='probes_in_block',
        ),
        migrations.AddField(
            model_name='probe',
            name='last_in_block',
            field=models.BooleanField(default=0, verbose_name='Проба является последней в блоке'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='probe',
            name='probe_number',
            field=models.IntegerField(verbose_name='Порядковый номер предложения'),
        ),
    ]
