# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import localizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0012_probe_probe_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='probe_control_conditions',
            field=models.CharField(default=localizer.models.assign_control_condition, max_length=200),
        ),
    ]
