# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0013_auto_20171008_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
