# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0014_subject_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response_sound_file_path',
            field=models.URLField(),
        ),
    ]
